// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppRestaurant.Data;

namespace WebAppRestaurant.Migrations
{
    [DbContext(typeof(WebAppRestaurantContext))]
    partial class WebAppRestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAppRestaurant.Models.Dish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ingredientsid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ingredientsid");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Ingredients", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("discount")
                        .HasColumnType("float");

                    b.Property<int?>("statusid")
                        .HasColumnType("int");

                    b.Property<int?>("tableid")
                        .HasColumnType("int");

                    b.Property<int?>("workerid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("statusid");

                    b.HasIndex("tableid");

                    b.HasIndex("workerid");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.OrderItem", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Orderid")
                        .HasColumnType("int");

                    b.Property<int?>("dishid")
                        .HasColumnType("int");

                    b.Property<int>("numberOfItems")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Orderid");

                    b.HasIndex("dishid");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.OrderStatus", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("OrderStatus");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Table", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Worker", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Dish", b =>
                {
                    b.HasOne("WebAppRestaurant.Models.Ingredients", "ingredients")
                        .WithMany()
                        .HasForeignKey("ingredientsid");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.Order", b =>
                {
                    b.HasOne("WebAppRestaurant.Models.OrderStatus", "status")
                        .WithMany()
                        .HasForeignKey("statusid");

                    b.HasOne("WebAppRestaurant.Models.Table", "table")
                        .WithMany()
                        .HasForeignKey("tableid");

                    b.HasOne("WebAppRestaurant.Models.Worker", "worker")
                        .WithMany()
                        .HasForeignKey("workerid");
                });

            modelBuilder.Entity("WebAppRestaurant.Models.OrderItem", b =>
                {
                    b.HasOne("WebAppRestaurant.Models.Order", null)
                        .WithMany("orderItem")
                        .HasForeignKey("Orderid");

                    b.HasOne("WebAppRestaurant.Models.Dish", "dish")
                        .WithMany()
                        .HasForeignKey("dishid");
                });
#pragma warning restore 612, 618
        }
    }
}
